import { AfterViewInit, OnChanges, SimpleChanges } from '@angular/core';
export declare class NgxTypedJsComponent implements AfterViewInit, OnChanges {
    cursorColor?: string;
    strings: string[];
    stringsElement?: string;
    typeSpeed: number;
    startDelay?: number;
    backSpeed?: number;
    smartBackspace?: boolean;
    shuffle?: boolean;
    backDelay?: number;
    fadeOut?: boolean;
    fadeOutClass?: string;
    fadeOutDelay?: number;
    loop?: boolean;
    loopCount?: number;
    showCursor?: boolean;
    cursorChar?: string;
    autoInsertCss?: boolean;
    attr?: string;
    bindInputFocusEvents?: boolean;
    contentType?: string;
    private completed;
    private preStringTyped;
    private stringTyped;
    private lastStringBackspaced;
    private typingPaused;
    private typingResumed;
    private reset;
    private stopped;
    private started;
    private destroyed;
    private typed;
    private content;
    ngAfterViewInit(): void;
    toggle(): void;
    stop(): void;
    start(): void;
    destroy(): void;
    doReset(restart?: boolean): void;
    private get options();
    private updateCursorStyle;
    ngOnChanges(changes: SimpleChanges): void;
}
